project: 
  type: website
  resources:
    - supplement/custom-vsm-schema.json

website: 
  page-navigation: true
  title: "VSM Flowchart"
  site-url: "https://shannonrankin.github.io/vsm-flowchart/"
  repo-url: "https://github.com/shannonrankin/vsm-flowchart"
  repo-actions: [edit, source, issue]
  favicon: favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/79/NOAA_logo.svg"
    favicon: favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://shannonrankin.github.io/vsm-flowchart/
        text: "Value Stream Management Toolbox"
      - icon: github
        href: https://github.com/shannonrankin/vsm-flowchart
        text: "VSM Flowchart repository"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - section: "Family Process Matrix"
        contents:
          - href: process-intro.qmd
            text: Overview
          - href: process-example.qmd
            text: Tutorial and Example
          - href: process-primary.qmd
            text: Interactive Workspace
          - href: process-next.qmd
            text: Next Steps
      - section: "Current State Map"
        contents:
          - href: current-intro.qmd
            text: Overview
          - href: current-example.qmd
            text: Tutorial and Example
          - href: current-primary.qmd
            text: Interactive Workspace
          - href: current-next.qmd
            text: Next Steps
      - section: "Future State Map"
        contents:
          - href: future-intro.qmd
            text: Overview
          - href: future-example.qmd
            text: Tutorial and Example
          - href: future-primary.qmd
            text: Interactive Workspace
          - href: future-next.qmd
            text: Next Steps

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
